### PR TITLE
DelayedArray, Orthologues, Ingest data, Plots, Normalize, Utilities 

### PR DESCRIPTION
**Pull request by bschilder**
## DelayedArray enhancements  
Previously,  `generate.celltype.data()` and `drop.uninformative.genes()` ran into memory problems, [described in this issue](https://github.com/NathanSkene/EWCE/issues/8).
These enhancements permit the analysis of arbitrarily large datasets by only pulling chunks of the full data into memory at a time. Operations on those chunks can then be parallelized across cores.
- Enable DelayedArray processing of `generate.celltype.data()`. 
- Enable DelayedArray and DGE using [glmGamPoi](https://github.com/const-ae/glmGamPoi) in `drop.uninformative.genes()`.
- [Useful workshop ](https://petehaitch.github.io/BioC2020_DelayedArray_workshop/articles/Effectively_using_the_DelayedArray_framework_for_users.html) for understanding how DelayedArray objects work and why they can be useful for large datasets.  

## filter_nonorthologues
This new function (and its support functions) is located within *filter.genes.without.1to1.homology.r*.  
- Add more robust `filter_nonorthologues()` function to replace `filter.genes.without.1to1.homology.r`.  
- Is able to convert genes from **21 model species to human orthologues**. See `taxaID_dict()` for full list.
- Relies upon the more general `convert_orthologues()` support function.
- Utilizes the [homologene](https://github.com/oganm/homologene) R package. 

## ingest_data
Added new function `ingest_data()` to import scRNAseq datasets across a wide range of formats. Once ingested, these datasets can be passed along to other EWCE functions that can recognize and use the SingleCellExperiment format.  
1. Takes `obj`, which can be either a path to a dataset file, or the object itself.
2. Infers the file format or object class, and imports it 
3. Converts the object to a SingleCellExperiment with a sparse DelayedArray.  
4. Optionally allows you to save the SingleCellExperiment as an`HDF5SummarizedExperiment`, which allows you to interact with the dataset without loading the full thing into memory at once, and/or take advantage of DelayedArray chunking functions.   

Current formats accepted:
- **Stored Rdata or RDS**: *.rds, .rda, .rdata*. Will automatically infer object class onced loaded into R.  
- **Raw matrix**: *.tsv, .csv, .mtx* (can be *.gz* compressed) or `data.frame, data.table, matrix (any subclass)`.  
- **Matrix folder**: Provide the path to an folder containing the uncompressed matrix, col data, and row data (e.g. *GSE107451_DGRP-551_w1118_WholeBrain_57k_0d_1d_3d_6d_9d_15d_30d_50d_10X_DGEM_MEX.mtx.tsv.tar.gz* in [GSE107451](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE107451) after unpacking it with `tar -xzf <targz_path>` in command line).
- **anndata**: *.h5ad*, path to anndata file or anndata imported using the `anndata` R package.  
- **Seurat or .h5seurat**: Path to saved Seurat file or *.h5seurat* (Seurat's h5 extension), or the Seurat object itself.  
- **loom**: Path to loom file stored on disk or the loom pointer object.
- **HDF5Array, SummarizedExperiment, SingleCellExperiment**: Path to files or objects.

## plot_gene_metrics  
New function in *plot_gene_metrics.R*.   
- `plot_gene_metrics`: Plot "mean_exp", "specificity", or "specificity_quantiles", at any annotation level.  
- Has filtering arguments to prioritize/limit genes and cell-types, increasing plot readability.

## find_celltype_markers
New function in *find_celltype_markers.R*.
- `find_celltype_markers()`: Takes a CTD object and identifies the genes with the highest cell-type specificity.  

## scT_normalize  
Located in *scT_normalize.R*.
- `scT_normalize()`: Wrapped scTransform normalization procedure into an easy-to-use function.

## Utility functions
New general support functions:
- `printer()` and `messager()`: control messages given to user, shut off with `verbose=F`.
- `assign_cores()`: Automatically detects the number of available cores and assigns ~90% of them as workers (using `BiocParallel`) for chunked DelayedArray objects.
- `create_DT()`: Let's users generate interactive, scrollable data tables with buttons to download it in different formats (e.g. csv, excel, pdf, etc).

## Package documentation
Added *package.R*, which gives users a general description of EWCE when they type `?EWCE`.  

## DESCRIPTION  
Updated Suggests/Imports/Remotes to support new functions.  When possible, kept in Suggests to minimize EWCE installation time.

### CODE REVIEW

**Comment by NathanSkene** [comment]
Hi Brian, just looked into merging this and saw that the travis checks have failed, can you look into getting them so they complete?

Also, are there any small example files for the new loading functions? Would be good if there were, and if loading if them was tested as part of the vignette (in a manner that people can see where the example files are).

**Comment by bschilder** [comment]
Made several fixes:
- Travis check originally failed bc I accidentally typed `:` instead of `::` in one of the DESCRIPTION remotes.  
- `loomR` is not available for this R version, which is sometimes used by `ingest_data()`. So I will remove this but provide a warning to users when it's required.  

Made several upgrades as well:
- Further extended `drop.uninformative.genes()` capabilities by making limma/DESeq2/glmGamPoi as different options. Since these methods can be computationally intensive, added some more pre-filtering options, like removing non-orthlogues or simply removing genes with low variance across cell-type means. 
- To  demonstrate these new features, I made a vignette: `vignettes/ingest_data.Rmd`.
- Added Seurat `pbmc_small` dataset to demonstrate the ability of `ingest_data()` to detect and convert various scRNAseq dataset formats.

**Comment by NathanSkene** [comment]
New changes sound great, very welcome improvements to the package!

Looks like the latest commits are still failing in Travis. @Al-Murphy is working on various improvements to the package at the moment, so I suggest we merge this as follows:
- @bschilder get's these commits building successfully
- @Al-Murphy pulls his tests into dev
- @bschilder's changes get pulled into dev
- We confirm that all the tests still work once @bschilder's changes are merged
- Consider any additional tests that should be added to confirm the new changes stay functional
- Then we consider merging to master (though we should probably also complete any checks required for bioconductor release before that)

**Comment by Al-Murphy** [comment]
Hey @bschilder, @NathanSkene,

Just to note, my tests and package script changes have been pushed to the dev branch and passed the travis tests.

**Comment by bschilder** [comment]
Hmm, looks like`biomaRt` installation is failing. Not sure why though, I don't think I change anything about how`biomaRt` is installed in the DESCRIPTION file (it's still listed under **Imports:**). 

```
Error: package or namespace load failed for ‘biomaRt’:
 .onLoad failed in loadNamespace() for 'biomaRt', details:
  call: httr::set_config(new_config, override = FALSE)
  error: object 'new_config' not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/travis/R/Library/biomaRt’
Error in i.p(...) : 
  (converted from warning) installation of package ‘biomaRt’ had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
The command "Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
```

**Comment by NathanSkene** [comment]
Looks like someone else reported a similar issue recently:
https://github.com/grimbough/biomaRt/issues/40

**Comment by bschilder** [comment]
I see! So I suppose I could switch biomaRt installation to this remote branch in the DESCRIPTION (`github::grimbough/biomaRt@3_12_testing`), though the better long-term solution might be to just wait for them to push the fixed version to BioConductor. Do you have a preference @NathanSkene?

**Comment by NathanSkene** [comment]
I've set them building again on travis, sounds like it should solve itself
shortly so let's leave it for now

**Comment by NathanSkene** [comment]
Think there is a new error:

```
Warning: replacing previous import ‘biomaRt::select’ by ‘dplyr::select’ when loading ‘EWCE’
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘glmGamPoi’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘EWCE’
* removing ‘/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/RtmpvN8MPj/Rinst1765912603482/EWCE’*
```

Btw, rather than commiting again you can just go to https://travis-ci.org/github/NathanSkene/EWCE. Then click the 'restart' button, shown below:

image

**Comment by bschilder** [comment]
@NathanSkene good to know, thanks! 

That's weird, I just encountered this same error when trying to install the DelayedArray branch on the Rstudio server. But it shouldn't be coming up since I specify it as a remote in the DESCRIPTION:

```
Remotes:
    github::ChristophH/sctransform@*release,
    github::mojaveazure/seurat-disk,
    github::cellgeni/sceasy,
    github::const-ae/glmGamPoi
```

**Pull request closed without merging**
