### PR TITLE
EWCE 2.0

### PR DESCRIPTION
**Pull request by bschilder**
## Note on branches

I previously made all all my changes to the forked repo bschilder/EWCE on the DelayedArray branch. However, something got screwed up with the git history in that fork, and the only way to push to the main repo was to  clone the main repo (*NathanSkene/EWCE*), create a new branch called `bschilder_dev`, copy and paste all the files with my `DelayedArray` branch's edits into this repo, and then make a Pull Request from there. This means you won't have the incremental commits I made as I upgraded EWCE, but at least everything will be harmonized moving forward.
I'll delete my old forked repo and make any future edits on this *NathanSkene/EWCE@bschilder_dev* branch.

## Upgrades & new features

* All functions can now use lists and CellTypeDatasets (CTD) from any species 
and convert them to a common species (human by default) via `orthogene`.  
* Automated CTD standardisation via `standardise_ctd`.  
* Can handle (sparse) matrices.  
* Can create CTD from very large datasets using `DelayedArray` object class.  
* All functions automatically create appropriate gene backgrounds given species.  
* More modular, simplified vignettes.  
* Additional gene pre-filtering options (DESeq2, MAST, variance quantiles).  
* New/improved plotting functions (e.g. `plot_ctd`).  
* Added example bootstrapping enrichment results as *extdata* to 
speed up examples (documented in *data.R*). 
Accessed via `EWCE::example_bootstrap_results()`.
* Replaced Travis and R-CMD GHA workflows with check-bioc GHA workflow to automatically: Create a local Bioconductor Docker container, run R-CMD checks, 
run BiocCheck, and rebuild/deploy pkgdown site. Everything is passing all checks on all 3 platforms!

## To do

* Automatically build and push a Docker container for EWCE to Docker Hub during the GHA checks. This should be easier now since the new GHA workflow creates exactly that during checks. We just have to push it to the *neurogenomicslab* DockerHub at the end.

### CODE REVIEW

**Review by Al-Murphy — COMMENTED** [review]
.github/workflows/check-bioc-docker.yml:

`run_docker: 'false'` - Is this parameter in use? It is pushing to docker with a commit now correct? Also can you test to ensure a push to docker won't occur if a check is failed (either in EWCE or orthogene)

**Review by Al-Murphy — COMMENTED** [review]
.github/workflows/dockerhub.yml:

Ah okay so the push happens from a separate yml file then, that's fine but again I'd like it tested that this won't push with a failed check

**Review by Al-Murphy — COMMENTED** [review]
DESCRIPTION:

Update version to 1.3.1 to align with Bioconductor version control

**Review by Al-Murphy — COMMENTED** [review]
NEWS.md:

* Version 1.3.1 not 2.0.0
* Other than this it looks good but please review and ensure all your new features are there, this should be an information page for (advanced) users so let's make sure it's complete!

**Review by Al-Murphy — COMMENTED** [review]
R/assign_cores.r:
* Mention this and any other functions that can run in parallel in the NEWS file

R/bin_columns_into_quantiles.r
* "@param defaultBin Which bin to assign when there's only one non-zero quantile." - I'm not sure I understand what this parameter is doing from the description, can you elaborate a little?
* Your comment here explains it better "In situations where there's only one non-zero quantile, cut() throws an error." maybe add this or a shorter version to the parameter?
* Do you have an example of when this happens I'm struggling to understand the use case?
* Add a unit test for this case too please

R/bootstrap_enrichment_test.R:
* Not sure about the phrasing, is the second last full stop intentional?:
#' @param bg List of gene symbols containing the background gene list
#' (including hit genes). If \code{bg=NULL},
#'  an appropriate gene background will be created automatically.
#' if \code{geneSizeControl=TRUE}.
* add function call users can do to view all species to parameter description (and following to parameters):
@param genelistSpecies Species that \code{hits} genes came from
#' (no longer limited to just "mouse" and "human").
* This parameter description should be updated now that EWCE can automatically convert hit list species to human right?:
#' @param geneSizeControl Whether you want to control for
#' GC content and transcript length. Recommended if the gene list originates
#' from genetic studies (\emph{Default: FALSE}).
#'  If set to \code{TRUE}, then \code{hits} must be from humans.
#' should be used rather than mouse.

R/calculate_meanexp_for_level.R
* Add unit tests for the issues you describe here:
"#### Guards against issues with DelayedArray"

R/calculate_specificity_for_level.R
* Again make sure the unit test above covers this, obv same one should:
"#### Guards against issues with DelayedArray"

R/controlled_geneset_enrichment.r
* default reps is 10,000 here but 100 in bootstrap_enrichment test, change one to be consistent

R/create_list_network.R
* add description of function and parameters even though internal, it's good to have for us
* Not sure what numBOOT does but if it is number of bootstrap, let's make the default consistent with what I said above too.

R/create_quadrants.R
* add description of function and parameters even though internal, it's good to have for us

R/ctd_to_sce.R
* Add parameters (I know this is a copied function but worth having locally)

R/delayedarray_normalize.R
* add description of function and parameters even though internal, it's good to have for us

R/drop_nonexpressed_cells.R
* add description of function and parameters even though internal, it's good to have for us

R/drop_nonexpressed_genes.R
* add description of function and parameters even though internal, it's good to have for us

R/drop_uninformative_genes.r
* description doesn't make it clear that there are other options now to remove genes that don't vary. Expand on this please!
* #' @param DGE_method Which method to use for the Differential Gene Expression
#' (DGE) step. - list out the options for the user.
* #' @param input_species Which species the gene names in \code{exp} come from.
#' @param output_species Which species' genes names to convert \code{exp} to. - again give the users a function to list all available species
*adj_pval_thresh = 0.00001, - this seems odd to me that's it's so low, why not just 0.05? I get you may have some FP's but surely EWCE will deal with these? Has an analysis been done comparing the different DEG approaches against a benchmark dataset? I think this is important to do since this is a key part of your expansion on EWCE. I imagine you will publish this version of EWCE right? This would form a fundamental part of that paper.
* no_cores = 1, - again parallel capacity should be in vignette/NEWS file

R/dt_to_df.R
* add description of function and parameters even though internal, it's good to have for us

R/ewce_expression_data.r
* #' @param tt Differential expression table.
#' Can be output of \link[limma]{topTable} function.
#' Minimum requirement is that one column stores a metric of - list other DEG methods available too

**Review by Al-Murphy — COMMENTED** [review]
R/ewce_plot.r
* ' \link[EWCE]{bootstrap_enrichment_test} or
#' \link[EWCE]{ewce_expression_data} functions.
#' Multiple results tables can be
#' merged into one results table, as long as the 'list' column is set to
#' distinguish them. - I would also state that the multiple testing is then calculated across all results - I don't think this idea is the clearest to all people

R/filter_variance_quantiles.r
* add description of function and parameters

R/get_ctd_levels.R
* add description of function and parameters

R/get_exp_data_for_bootstrapped_genes.R
* add description of function and parameters

R/get_sig_results.R
* add description of function and parameters

R/is_celltypedataset.R
* add description of function and parameters

R/is_delayed_array.R
* add description of function and parameters

R/is_matrix.R
* add description of function and parameters

R/is_sparse_matrix.R
* add description of function and parameters

R/max_ctd_depth.R
* add description of function and parameters

R/merge_sce_list.R
* add description of function and parameters

R/message_parallel.R / R/messager.R / R/myScalesComma.R
* add description of function and parameters

R/package.R
* What does this do? Haven't seen it before, is it just to give an explantion of the package? Can a user call it in R?

R/plot_bootstrap_plots.R
* add description of function and parameters

R/plot_log_bootstrap_distributions.R / R/plot_with_bootstrap_distributions.R
* add description of function and parameters

R/rNorm.R 
* add description of function and parameters

R/read_ctd.R / R/sce_merge_comparable_levels.R / R/zeisel2018_functions.r
* Why are these scripts kept and not just removed? They are all commented out

R/run_deseq2.R
* LRT is the correct default as it has been proven to be better than Wald but I think you should give the user the option to choose Wald too.
* More generally, I think you should add in edgeR as an DEG option, in our analysis of scRNA-Seq methods, edgeR performs better than DESeq2. See this [benchmark paper](https://www.biorxiv.org/content/10.1101/2021.03.12.435024v1.full) for the same results (fig 1(c)). Also you should offer the two test types of LRT and QLF but again LRT should be the default

R/sce_lists_apply.R / R/to_dataframe.R / R/to_delayed_array.R / R/to_sparse_matrix.R
* add description of function and parameters

README.Rmd
* Code coverage isn't showing which I guess is because this isn't the master branch right? Can you make a note to check this when the push is made to master?
* Installation instructions is for the dev branch can you specify this and add instructions for the current release

**Review by Al-Murphy — COMMENTED** [review]
Getting started vignette:
* Overall, I think this is a great idea with the vignettes! Can you add a quick description of the differences in the ctd levels, what they mean and how to use them? No need for code but just explain the differences biologically

Extended vignette:
* Can you add more of a description of the differences in the ctd levels, what they mean biologically? You have code for them but I think the explanation could be expanded. 
* Plot results from multiple sets of enrichment results section - can you add an explanation that multiple testing is applied across all studies in the list.
* Can you explain the different species EWCE can now be run with i.e. if your gene list isn't human can still use it etc
* Detail that certain parts can be run in parallel and name them (People ask this of packages frequently).

Create CTD vignette:
* In Calculate specificity matrices section - describe the different DEG methods for drop_uninformative_genes
* For the `cortex_mrna$exp_scT_normed <- EWCE::sct_normalize(cortex_mrna$exp) ` can you block the output of this R chunk? It takes up too much of the vignette

Docker vignette:
* This isn't in the README so won't be accessible in the website, can you add it?

Vignettes in general:
* Can you make a note to check all the links to the vignettes on the website work when you push to master?
* Did you run `devtools::build_site()` before pushing? In your new GHA and website push approach is this needed? I think it is still necessary as the website is built from the files in docs/articles/

**Review by Al-Murphy — COMMENTED** [review]
devtools check gives note which you will need to sort (remove git history of png's .RData objects should do it):
```
> checking installed package size ... NOTE
    installed size is  6.8Mb
    sub-directories of 1Mb or more:
      doc   6.3Mb
```

**Review by Al-Murphy — COMMENTED** [review]
Final overall notes that we (@bschilder @NathanSkene) need to discuss:
* Add unit tests covering new functionality
* List all the species EWCE can be used with
* If I understand correctly, by default you convert every species to human before running the analysis. Is there a chance you could loose information if the user wants to look at a mouse gene list in a mouse dataset (i.e. only 1:1 homologues would be kept). @bschilder @NathanSkene what do you both think?
* I believe some analysis into the different DEG methods for drop uninformative genes should be done on a known dataset (Made this point previously but I think edgeR should be added as a choice since it has been shown to outperform Deseq2). Does it actually make a difference which approach you use? Since we now offer more approaches I think this analysis is necessary and we should choose the best approach as the new default. @bschilder @NathanSkene, do you agree?
* I think the accumulation of changes to EWCE should be made into a manuscript with the above analysis as a key part. Do you both agree? Brian this would of course be your paper
* I think a manuscript of Orthogene should go up on BioRxiv as soon as possible and then we should instruct people who use this functionality in EWCE to cite it (it should go in the README at least but probably the vignettes too). Brian, even if it isn't ready to submit to a journal it should be up there for people to cite.

**Comment by bschilder** [comment]
> .github/workflows/check-bioc-docker.yml:
> 
> `run_docker: 'false'` - Is this parameter in use? It is pushing to docker with a commit now correct? Also can you test to ensure a push to docker won't occur if a check is failed (either in EWCE or orthogene)

This feature is not being used at the moment. ideally, it would be most efficient to build the Docker container once, test it, and push to DockerHub all in one workflow, but I couldn't get this working smoothly and opted to just use the separate dockerhub.yml workflow based on scFlow.

**Comment by bschilder** [comment]
# Checklist 

## R/assign_cores.r:
* [ ] Mention this and any other functions that can run in parallel in the NEWS file

## R/bin_columns_into_quantiles.r
* [ ] "@param defaultBin Which bin to assign when there's only one non-zero quantile." - I'm not sure I understand what this parameter is doing from the description, can you elaborate a little?
* [ ] Your comment here explains it better "In situations where there's only one non-zero quantile, cut() throws an error." maybe add this or a shorter version to the parameter?
* [ ] Do you have an example of when this happens I'm struggling to understand the use case?
* [ ] Add a unit test for this case too please

## R/bootstrap_enrichment_test.R:
* [ ] Not sure about the phrasing, is the second last full stop intentional?:
```
#' @param bg List of gene symbols containing the background gene list
#' (including hit genes). If \code{bg=NULL},
#'  an appropriate gene background will be created automatically.
#' if \code{geneSizeControl=TRUE}.
* add function call users can do to view all species to parameter description (and following to parameters):
@param genelistSpecies Species that \code{hits} genes came from
#' (no longer limited to just "mouse" and "human").
* This parameter description should be updated now that EWCE can automatically convert hit list species to human right?:
#' @param geneSizeControl Whether you want to control for
#' GC content and transcript length. Recommended if the gene list originates
#' from genetic studies (\emph{Default: FALSE}).
#'  If set to \code{TRUE}, then \code{hits} must be from humans.
#' should be used rather than mouse.
```

## R/calculate_meanexp_for_level.R
* [ ] Add unit tests for the issues you describe here:
"#### Guards against issues with DelayedArray"

## R/calculate_specificity_for_level.R
* [ ] Again make sure the unit test above covers this, obv same one should:
`"#### Guards against issues with DelayedArray"`

## R/controlled_geneset_enrichment.r
* [ ] default reps is 10,000 here but 100 in bootstrap_enrichment test, change one to be consistent

## R/create_list_network.R
* [ ] add description of function and parameters even though internal, it's good to have for us
* [ ] Not sure what numBOOT does but if it is number of bootstrap, let's make the default consistent with what I said above too.





## R/create_quadrants.R
* [ ] add description of function and parameters even though internal, it's good to have for us

## R/ctd_to_sce.R
* [ ] Add parameters (I know this is a copied function but worth having locally)

## R/delayedarray_normalize.R
* [ ] add description of function and parameters even though internal, it's good to have for us

## R/drop_nonexpressed_cells.R
* [ ] add description of function and parameters even though internal, it's good to have for us

## R/drop_nonexpressed_genes.R
* [ ] add description of function and parameters even though internal, it's good to have for us

## R/drop_uninformative_genes.r
* [ ] description doesn't make it clear that there are other options now to remove genes that don't vary. Expand on this please!
* [ ] `#' @param DGE_method`: Which method to use for the Differential Gene Expression
* [ ] `#' (DGE) step.` - list out the options for the user.
* [ ] `#' @param input_species` Which species the gene names in \code{exp} come from.
* [ ] `#' @param output_species` Which species' genes names to convert \code{exp} to. - again give the users a function to list all available species
* [ ] `adj_pval_thresh = 0.00001`, - this seems odd to me that's it's so low, why not just 0.05? I get you may have some FP's but surely EWCE will deal with these? Has an analysis been done comparing the different DEG approaches against a benchmark dataset? I think this is important to do since this is a key part of your expansion on EWCE. I imagine you will publish this version of EWCE right? This would form a fundamental part of that paper.
* [ ] `no_cores = 1`, - again parallel capacity should be in vignette/NEWS file

## R/dt_to_df.R
* [ ] add description of function and parameters even though internal, it's good to have for us

## R/ewce_expression_data.r
* [ ] `#' @param tt` Differential expression table.
```
#' Can be output of \link[limma]{topTable} function.
#' Minimum requirement is that one column stores a metric of - list other DEG methods available too
```

<hr>

## R/ewce_plot.r
* [ ]  I would also state that the multiple testing is then calculated across all results - I don't think this idea is the clearest to all people
```
 \link[EWCE]{bootstrap_enrichment_test} or
#' \link[EWCE]{ewce_expression_data} functions.
#' Multiple results tables can be
#' merged into one results table, as long as the 'list' column is set to
#' distinguish them. 
```

## R/filter_variance_quantiles.r
* [ ] add description of function and parameters

## R/get_ctd_levels.R
* [ ] add description of function and parameters

## R/get_exp_data_for_bootstrapped_genes.R
* [ ] add description of function and parameters

## R/get_sig_results.R
* [ ] add description of function and parameters

## R/is_celltypedataset.R
* [ ] add description of function and parameters

## R/is_delayed_array.R
* [ ] add description of function and parameters

## R/is_matrix.R
* [ ] add description of function and parameters

## R/is_sparse_matrix.R
* [ ] add description of function and parameters

## R/max_ctd_depth.R
* [ ] add description of function and parameters

## R/merge_sce_list.R
* [ ] add description of function and parameters

## R/message_parallel.R / R/messager.R / R/myScalesComma.R
* [ ] add description of function and parameters

## R/package.R
* [ ] What does this do? Haven't seen it before, is it just to give an explantion of the package? Can a user call it in R?

## R/plot_bootstrap_plots.R
* [ ]add description of function and parameters

## R/plot_log_bootstrap_distributions.R / R/plot_with_bootstrap_distributions.R
* [ ] add description of function and parameters

## R/rNorm.R 
* [ ] add description of function and parameters

## R/read_ctd.R / R/sce_merge_comparable_levels.R / R/zeisel2018_functions.r
* [ ] Why are these scripts kept and not just removed? They are all commented out

## R/run_deseq2.R
* [ ] LRT is the correct default as it has been proven to be better than Wald but I think you should give the user the option to choose Wald too.
* [ ] More generally, I think you should add in edgeR as an DEG option, in our analysis of scRNA-Seq methods, edgeR performs better than DESeq2. See this [benchmark paper](https://www.biorxiv.org/content/10.1101/2021.03.12.435024v1.full) for the same results (fig 1(c)). Also you should offer the two test types of LRT and QLF but again LRT should be the default

## R/sce_lists_apply.R / R/to_dataframe.R / R/to_delayed_array.R / R/to_sparse_matrix.R
* [ ] add description of function and parameters

## README.Rmd
* [ ] Code coverage isn't showing which I guess is because this isn't the master branch right? Can you make a note to check this when the push is made to master?
* [ ] Installation instructions is for the dev branch can you specify this and add instructions for the current release

<hr>

## Getting started vignette:
* [ ] Overall, I think this is a great idea with the vignettes! Can you add a quick description of the differences in the ctd levels, what they mean and how to use them? No need for code but just explain the differences biologically

## Extended vignette:
* [ ] Can you add more of a description of the differences in the ctd levels, what they mean biologically? You have code for them but I think the explanation could be expanded. 
* [ ] Plot results from multiple sets of enrichment results section - can you add an explanation that multiple testing is applied across all studies in the list.
* [ ] Can you explain the different species EWCE can now be run with i.e. if your gene list isn't human can still use it etc
* [ ] Detail that certain parts can be run in parallel and name them (People ask this of packages frequently).

## Create CTD vignette:
* [ ] In Calculate specificity matrices section - describe the different DEG methods for drop_uninformative_genes
* [ ] For the `cortex_mrna$exp_scT_normed <- EWCE::sct_normalize(cortex_mrna$exp) ` can you block the output of this R chunk? It takes up too much of the vignette

## Docker vignette:
* [ ] This isn't in the README so won't be accessible in the website, can you add it?

## Vignettes in general:
* [ ] Can you make a note to check all the links to the vignettes on the website work when you push to master?
* [ ] Did you run `devtools::build_site()` before pushing? In your new GHA and website push approach is this needed? I think it is still necessary as the website is built from the files in docs/articles/

<hr>

* [ ] devtools check gives note which you will need to sort (remove git history of png's .RData objects should do it):
```
> checking installed package size ... NOTE
    installed size is  6.8Mb
    sub-directories of 1Mb or more:
      doc   6.3Mb
```

* [ ] Code coverage check with `devtools::test_coverage()` gave ~70%, Brian I think you need to add more tests to cover the new functionality. We should aim for 80% coverage but more importantly make sure all new functionality is thoroughly tested

**Comment by Al-Murphy** [comment]
In the description, you have now changed it to 1.3.2 since you made additional changes. However since these first batch of changes weren't pushed to bioconductor it should still be 1.3.1. Can you revert?

**Comment by bschilder** [comment]
> In the description, you have now changed it to 1.3.2 since you made additional changes. However since these first batch of changes weren't pushed to bioconductor it should still be 1.3.1. Can you revert?

Oh i see, didn't realize that bioc doesn't let you skip versions. Np, changing it back.

**Comment by Al-Murphy** [comment]
Notes:
* news.md file lists changes in 1.3.1 and 1.3.2 separately but we reverted to 1.3.1 numbering so just merge these.
* Add documentation (description and paramterts) to `calculate_specificity_for_level`, `bootstrap_plot`, `cell_list_dist`, `check_annotLevels`, `check_args_for_bootstrap_plot_generation`,`check_bootstrap_args`,`
check_controlled_args`, `check_ewce_expression_data_args`, `check_full_results`, `check_generate_controlled_bootstrap_geneset`, `check_species`, `check_nas`, `check_group_name`, `check_numeric`, `get_exp_data_for_bootstrapped_genes`, `get_graph_theme`, ``
* For `delayedarray_normalize.R` - Is there a unit test to check this gives the same result as original (not delayed matrix) approach? If not, can you add one? 
* Similar to the above, consider if all tests are in place for new features but also where new ways of implmenting the same functions in EWCE have been used. These should give the exact same results as before and should be tested for that. Other than this, I get the coverage at 83% which is pretty good so I'm happy enough with that.
* For `sce_merge_comparable_levels.R`, this is all commented out, can it be removed?
* README:
    * "*EWCE* requires [`R>=4.1`](https://www.r-project.org/) and `Bioconductor>=1.4`"  - Should be `Bioconductor>=3.14`
    * Vignettes still aren't available at README link, make a note to check this for when it is merged
* Two CRAN check notes that still need to be sorted:
```
── R CMD check results ────────────────────────────────────────────────────────────────────────────────────── EWCE 1.3.1 ────
Duration: 16m 13.7s

> checking installed package size ... NOTE
    installed size is  6.9Mb
    sub-directories of 1Mb or more:
      doc   6.3Mb

> checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘doc’
```

**Comment by bschilder** [comment]
- [x] news.md file lists changes in 1.3.1 and 1.3.2 separately but we reverted to 1.3.1 numbering so just merge these.
- [ ] Add documentation (description and parameters) to calculate_specificity_for_level, bootstrap_plot, cell_list_dist, check_annotLevels, check_args_for_bootstrap_plot_generation,check_bootstrap_args, check_controlled_args, check_ewce_expression_data_args, check_full_results, check_generate_controlled_bootstrap_geneset, check_species, check_nas, check_group_name, check_numeric, get_exp_data_for_bootstrapped_genes, get_graph_theme, ``
- [ ] For delayedarray_normalize.R - Is there a unit test to check this gives the same result as original (not delayed matrix) approach? If not, can you add one?
- [ ] Similar to the above, consider if all tests are in place for new features but also where new ways of implmenting the same functions in EWCE have been used. These should give the exact same results as before and should be tested for that. Other than this, I get the coverage at 83% which is pretty good so I'm happy enough with that.
- [ ] For sce_merge_comparable_levels.R, this is all commented out, can it be removed?
README:
 + "EWCE requires R>=4.1 and Bioconductor>=1.4" - Should be Bioconductor>=3.14
+ Vignettes still aren't available at README link, make a note to check this for when it is merged
- [ ] Two CRAN check notes that still need to be sorted:
```R
── R CMD check results ────────────────────────────────────────────────────────────────────────────────────── EWCE 1.3.1 ────
Duration: 16m 13.7s

> checking installed package size ... NOTE
    installed size is  6.9Mb
    sub-directories of 1Mb or more:
      doc   6.3Mb

> checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘doc’
```

**Comment by bschilder** [comment]
Yay!!! 🍾

**Comment by NathanSkene** [comment]
Great work, very happy to see this, getting EWCE working with big datasets was basically the first thing I wanted done back when the lab started, thanks for getting it here!

Merry christmas!
________________________________

**Pull request merged**
